# Generated by Django 3.2.23 on 2023-12-01 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_matrixtranspose'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatrixInverse',
            new_name='MatrixInverseTranspose',
        ),
        migrations.DeleteModel(
            name='MatrixTranspose',
        ),
        migrations.RenameField(
            model_name='matrixinversetranspose',
            old_name='inverse',
            new_name='result',
        ),
    ]
